---
title: The movement patterns of free-roaming dogs inhabiting an offshore island of
  Singapore
author: "Dajun Wang"
date: "11/9/2019"
output:
  pdf_document:
    toc: no
    number_sections: TRUE #auto-number chapters
    fig_caption: yes
    df_print: kable
    highlight: tango
  html_document:
    toc: no
    df_print: paged
fontsize: 11pt
geometry: margin = 1.2in
bibliography: ["zot-library.bib"]
editor_options:
  chunk_output_type: console
spacing: double
mainfont: Times New Roman
header-includes:
- \setlength\parindent{24pt}
- \usepackage{indentfirst}
- \usepackage{setspace}\doublespacing
---
```{r global options, cache=FALSE, include=FALSE}
set.seed(2807)
knitr::opts_chunk$set(fig.pos = 'H') #to set all images to top
knitr::read_chunk('lit-review.Rmd')
options(tinytex.verbose = TRUE)
```

# Overview

Establishing or restoring ecosystem health is a critical goal for conservation biologists and ecologists, and one of the major causes for concern is the introduction of non-native species into an ecological community [@macdonaldIntroducedSpeciesLine2008]. Unfortunately, the migration and distribution of human populations across the globe gave rise to the purposeful or incidental introduction of many species (including domestic commensals) into a vast range of habitats and consequently, ecosystems. This phenomenon can be problematic for biodiversity conservation as the introduction of non-native species can further 'weaken' an ecosystem that is already affected by habitat fragmentation and degradation. As such, introduced species may assume the role of a convenient scapegoat aimed at misdirecting attention from more fundamental systemic issues such as habitat loss. For example, @gurevitchResponseRicciardiAssessing2004 argues that the rapid rate of extirpation in unionid mussels was caused by poor habitat management (e.g., degradation, pollution) and not due to the (commonly assumed) introduction of the invasive Zebra mussles (*Dreissena polymorpha*).

Domestic commensals living with strong associations with human communities can be problematic for biodiversity conservation especially when these animals are intricately tied to the economic, social, and political values and views of the human community[@simberloffBiologicalInvasionsHow2001].  For example, @medinaGlobalReviewImpacts2011 reviewed that the domestic free-roaming cat (*Felis silvestris catus*) are the primary drivers for at least 14% of the global bird, mammal, and reptile extinctions and are a prominent threat to almost 8% of critically endangered birds, mammals, and reptiles. This is, in part, due to a myriad of reasons: 1) cats were displaced globally, including many remote islands, alongside human migration[@medinaGlobalReviewImpacts2011], 2) cats are dietary generalists and will consume a large variety of prey [@camposDietFreerangingCats2007; @forsythHowDoesCarnivore2014], 3) most native island species have naive defences against mammalian predators[kierGlobalAssessmentEndemism2009] , hence the extinctions of insular endemic and local island species populations were largely driven by the introduced free-roaming cat.

Despite being the one of the most abundant carnivores in the world [@youngWildlifeGoingDogs2011], the domestic dog (*Canis familiaris*) has received far lesser notice despite being a major problem in many urban and natural landscapes, and potential predators of or competitors with a wider variety of native speices in comparison to the domestic cat [@feldmannProblemUrbanDogs1974]. Unfortunately, the scarcity of information on the environmental and ecological effects of the free-roaming dog (FRD) stems from lack of scientific examination on the domestic dogs' potential population-level impacts [@hughesReviewInteractionsFreeroaming2013], anecdotally reports on canid-wildlife conflicts[@mitchellWildDogsExclude2005] or poorly studied roles within an ecosystem[@flemingRolesCanidaeFood2017]. As such, there is a need to study and understand the roles and impacts of these animals so as to enhance the efficacy and progress of biodiversity conservation initiatives in dog-present landscapes and facilitate the recovery and maintenance of global and/or local wildlife populations.


# The origin of the domestic dog

The global estimate for the domestic dog population is seldom reported and such estimates are typically derived from unclear methodologies [@gompperDogHumanWildlife2013]. For example, large-scale estimates are often
derived through dog:human ratios which are the result of diverse survey methods and density estimations produced by pet product manufacturers, veterinary associations and establishments, and animal welfare shelters or organisations [@gompperDogHumanWildlife2013]. That being said, the most recent global-level estimate for dog numbers within the present literature was cited at 700 million dogs by @hughesReviewInteractionsFreeroaming2013, and this estimate is expected to increase in tandem with the growth and expansion of human populations.

Unfortunately, the estimates obtained from the dog:human ratio are typically derived derived from a single point in time; multiple estimates rarely exist especially for countries without a national unified system for dog population management [@gompperDogHumanWildlife2013]. In addition, there will be difficulties in accounting for dog numbers derived from different degrees of dog ownership between regions, and the unaccountable presence of free-roaming dogs. For example, differences in regional estimates of dog numbers may be influenced by the societal norms of local dog ownership as well as local dog management strategies. More importantly, dogs are often dependent on resources supplemented by humans and the fluctuations in dog numbers can arise from differences in waste disposal practices and management, and the availability of human-derived resources (e.g., medicine, shelters) in urban, rural and natural areas. As such, the dog:human ratios can differ greatly between urban and rural landscapes, and between countries and regions [@gompperDogHumanWildlife2013]. For example, the owned domestic dog population in the United States increased by 3 to 4% annually while an inverse pattern was observed in Australia, where the owned domestic dog populations declined by 15% between 1998 to 2009 [@gompperDogHumanWildlife2013].

From a taxonomic perspective, the term ‘dog’ can be ambiguous and confusing. Having evolved from the gray wolf (*Canis lupus*), the domestic dog (*C. familiaris*) is still regarded as a subspecies of the wolf despite being phenotypically distinct [@gompperIntroduction2013]. In addition, subsequent evolution of the introduced domestic dog, the dingoe (*C. lupus dingo*), in the Australianb landscape further confounds the contentious delineation between the domestic dog, their wild and feral counterparts (e.g., coyote (*C. latrans*), jackals (*C. mesomelas*)), and their hybrids (e.g., coydog (*C. latrans* × *C. lupus familiaris*), wolfdog). For all intents and purposes, I refer to the term ‘dog’ specifically to address the domestic dogs while terms pertaining to their wild or hybrid counterparts (e.g., dingoes, coyotes) will be specifically mentioned. In addition, owing to the general lack of domestic dog-related studies in the present state of canid literature, references to the domestic dogs' wild counterparts may be used to exemplify (dis)-similarities of the ecological role within the members of the Canidae family.

A genomic study into the evolutionary origins of the dog suggests that the domestication relationship between humans and *Canis* occured after the origin of domestic plants and agriculture where the shift away from a more carnivorous diet catalyzed the domestication of the dog [@larsonHowMuchThat2014]. As such, the association with humans (e.g., food dependency) appears to be the stimulas for the close relationship between primitive *Canis* and humans, which is still being presently observed in modern times. For example, today's domestic dogs take on complex and diverse roles (e.g., as pets, working or protection animals) with varying levels of integration into different types of human communities. Even when not owned, the direct and indirect dependency on human-derived materials (e.g., food, shelter, protection) has mirrored the dogs' tremendous growth and distribution with the growth and expansion of human population and settlements across the globe.

Outside of roles defined by human ownership (e.g., pets, working dogs), there have been many efforts made to define and describe the categories of 'unowned' dogs [@gompperDogHumanWildlife2013]. For example, @banksFourleggedFriendFoe2007 differentiates the domestic dog plainly between owned and unowned, while other nomenclatures includes rural, village, feral, wild and free-roaming [@boitaniComparativeSocialEcology1995; @butlerDietFreerangingDomestic2002; @flemingManagingImpactsDingoes2001; @manorImpactFreeroamingDogs2004; @ruiz-izaguirreVillageDogNot2013, respectively] were used contextually to ecologically characterise the domestic dog. However, most authors would agree that these categories are flexible and non-restrictive as dogs are likely to switch or fall into more than one category [@vanakDogsCanisFamiliaris2009]. Therefore, to reduce the confounding terms and complexity of categorising dogs, it could be more meaningful to examine the dogs' ecological impact and function through the spatial and circumstantial context of their ownership (or lack of).

# The ecological impact of the free-roaming dog

Regardless of ownership, the domestic dog is dependent on the provision human-derived supplementary resources (e.g., commercially prepared pet food) or foods that were scavenged (e.g., foraging for human refuse). In a natural landscape, the provision of supplementary resources, regardless of intent, are often an ecologial subsidy and will facilitate the population growth of animals that subsists on them. For example, @webbCommonRavenJuvenile2004 reported that anthropogenic subsidies (e.g., human refuse and waste) have signifcantly contributed to the dramatic increase in the abundance of the Common ravens (*Corvus corax*) and @burgerHabitatChoiceDisturbance2007 noted similar findings with the glaucous gulls (*Larus hyperboreaus*) and shorebirds in a migratory stopover. In addition to population density increases, the provision of supplementary resources can lead to behavioural pattern shifts as observed in wild Slovenian red deers (*Cervus elaphus*) developing smaller home range  sizes (e.g., reduced extent and/or frequency of roaming patterns) after being supplementally fed by hunters to increase their value [@jerinaRoadsSupplementalFeeding2012].

Being an adaptable generalist has provided dog populations the capacity to attain higher densities in comparison to their wilder counterparts, particularly in landscapes where dogs are viewed upon commensally . This is true in urban or semi-rural landscapes where the free-roaming domestic dog have been reported to opportunistically capitalize (i.e., reduced territoriality, increased foraying distances) on the availability of food and shelter (e.g., garbage sites @tiwariUtilisingGroupSizeHomeRange2019) in human communities or climatic events (e.g., religious feasts, stormy weather; @tiwariComparativeStudyEnumeration2018), especially when they are not the intentional receipient of said resources[@butlerAnthropogenicFoodSubsidy2018]. For example, dog population densities have been found to range from 468 dogs per km2 in semi-urban Philippines [@childsDensityEstimatesRural1998] to 6 – 21 dogs per km^2^ in rural Kenya [@kitalaDogEcologyDemography2001] in comparison to coyote populations ranging from 0.2 to 0.44 per km^2^ and wolf populations from 0.005 to 0.4 per km2 [@carboneCommonRuleScaling2002]. 

With the capacity to loosely form yet highly territorial groups [@gompperDogHumanWildlife2013], the artificially enhanced free-roaming dog population may result in the increase in predation pressure on prey species where their rate of predation can exceed the rate of consumption and the energetic requirements of said predator (i.e., surplus killing). Surplus killing is a commonly seen predatory behaviour in canid species for two primary reasons: (1) ineffective prey response due to novel interactions with introduced dogs and (2) large packs of dogs are capable of defending kills and continue hunting despite having acquired sufficient food (see Kruuk 1972). An Australian study reported 83 red kangaroos (*Macropus rufus*) were preyed upon by a pack of five dingoes over a period of seven weeks and the dogs were only consuming portions from half of the killed kangaroos [@shepherdPredationRedKangaroos1981]. Similarly, @bayarbaatarMongolianSaigaSharga2009 noted that free-roaming dogs may be a threat to Saigas during harsh winter condition when saigas are in poor health, as well as in stages of neonate birthing and rearing where dogs have reportedly consumed more than 10,000 calves annually.

Apart from affecting prey numbers, artifically enhanced populations not only provides the free-roaming dogs with the numerical advantage to outcompete other predator species in acquiring resources, it also provides the dogs the capacity to compete with a wider range of top predators (e.g., wolves; *C. lupus*), mesopredators (e.g., jackals; *C. mesomelas*), as well as non-mammalian carnivores (e.g., monitor lizards *Varanus spp.*) in semi-rural or urban landscapes [@vanakTopdogsUnderdogs2013]. In Zimbabwe, @butlerDietFreerangingDomestic2002 reported that free-roaming dogs monopolized the supply of domestic animal carrion and outcompeted the principal competitors (e.g., vultures, lions (*Panthera leo*) and spotted hyaenes (*Crocuta crocuta*)) on the peripheries of reserves owing to their high densities (6.5% growth per annum), physical and numerical dominance and greater tolerance to anthropogenic disturbances.

However, not all forms of ecological subsidy gave rise to negative interaction effects. Even though occuring in large densities (10 dogs km^-2^), [@atickemCompetitionDomesticDogs2009] reported that fecal analysis showed no overlap in the diet as well as home ranges between the Ethiopian wolf (*C. simensis*) and the free-roaming dogs. This is because the dogs were found to depend almost entirely on human-derived foods (> 70%) while the wolves had a diet consisting primarily of rodents. Similarly, @athreyaCatDogsLeopard2016 found that leopards (*Panthera pardus*) subsisted almost completely on domestic livestock (e.g., goats, cows) but
dogs played the most important food resource (39% of entire diet). Yet, despite the selection pressure for domestic dogs and cats (hence the reduced economic pressure of depredation), the human-leopard conflict is still exacerbated by the sentimental value of the dog (to humans) and the encroachment into the close proximity to household with dogs.

As a relatively large-bodied predator, dogs can assume the role of an apex predator in a natural system free from a larger mammalian predator or a landscape where larger-bodied carnivores are persecuted. For example, the  dogs abandoned on Galapagos islands fulfilled the role of a missing apex predator and preyed on many native species (e.g., marine iguanas, nesting marine birds) that were naive to dogs as potential predators [@barnettFeralDogsGalapagos1983]. On a similar note, the dingo (and their domestic and hybridised counterparts) in mainland Australia dominated over most subordinate native mammalian predators during direct encounters [@dohertyContinentalPatternsDiet2019; @shortSurplusKillingIntroduced2002] due to their advantageous body size as well as their ability to hunt in packs. For example, @mitchellWildDogsExclude2005 found a high degree of overlap in the diet composition between dingoes (and wild dogs) and foxes which possibly resulted in temporal avoidance or localized habitat shifts in the two species. Therefore, it is not unlikely that the introduction of the dingoe into Australia played a significant role in the extinction of the thylacine (*Thylacinus cynocephalus*) and the Tasmanian devil (*Sacrophilus harrisii*)[@vanakTopdogsUnderdogs2013].

Asides from the lethal effects of predation, the mere presence of a predator can also affect prey species in subtle yet apparently harmful ways. For example, dogs may be able to suppress prey populations through non-consumptive means (e.g., harrassment) which can cause disruption of normal activities or states where anti-predatory behaviours such as increased vigilance, flight, refuge seeking and/or freezing would occur. This has been found in Israel where @manorImpactFreeroamingDogs2004 concluded that the presence of free-roaming dogs were a threat to the mountain gazelles (*Gazella gazella gazella*) recuitment, and their direct acts of harrassement (e.g., chasing of adult and kid ) were contributory to the gazelle's reduced reproductive success and survival. Similarly,  native bandicoots (*Paremeles nasuta*; [@cartheyWhenDoesAlien2012]) and Indian foxes (*Vulpes bengalensis*; [@vanakInterferenceCompetitionLandscape2010]) were less likely to forage and/or traverse through dog-dominated landscapes even when these areas were potentially higher in human-derived resources.

Another growing concern in the interaction between free-roaming dogs and wildlife lies in dog's potential role as disease vectors towards wildlife [@hughesReviewInteractionsFreeroaming2013]. Previously, a series of well publicized and large-scale die-offs of wild carnivore populations occured following the introducton of pathogenic viruses originating from free-roaming dog populations [@knobelDogsDiseaseWildlife2013]. As a result, this critical issue of addressing dog-transmissible diseases was quickly recognized as important drivers of wildlife population dynamics and demanded a multi-disciplinary approach despite the long-standing recognition in the importance of disease and health in wildlife conservation.

At present, dogs are the primary cause for 99% of the rabies-induced human fatalities reported worldwide [@tenzinFreeRoamingDogPopulation2015] and are hosts to more than 60 other transmissible zoonoses. Viruses that are particularly infectious towards carnivores such as canine distemper, parvovirus, rabies and rotavirus which can be found in the feces of un-vaccinated dogs [@yanDogsDiseaseThreats2020], and reports citing cross-species infections have been reviewed extensively by [@knobelDogsDiseaseWildlife2013]. A local example noted by [@mendenhallEvidenceCanineParvovirus2016] reported that two common palm civet cats (*Paradoxurus musangus*) tested PCR-positive for parvovirus infection, and the tested strain bears similarities to the Canine Parovirus (CPV) clade that have infected dogs in China and Uruguay. 

In spite of all the aforementioned interactions between dogs and wildlife, dogs can potentially assume a beneficial role and exert a positive impact through an ecosystem. In Australia, the presence of dingoes benefitted the native dusky hopping mice (*Notomys fuscus*) through the suppression of smaller mesopredators (e.g., feral cats and foxes; [@letnicTopPredatorsBiodiversity2012]), and this form of control over introduced species is a welcomed interaction. This is because the introduction of invasive species (such as cats and foxes) into the Australian ecosystem has been damaging; @woinarskiHowManyBirds2017a reviewed that feral cats in Australia killed 35.6 birds km^-2^ yr^-2^ and 99% of these mortalities were native bird species. 

Amidst the obvious risks (e.g., surplus killing, harrassment) imposed by dogs (and their wild counterparts) in an ecosystem, the value of introducing or conserving the dog in natural landscapes and ecosystems is worth debating. Canid researchers, particularly dingoe conservationists in Australia, proposes re-introducing the dingoe into degraded rangelands for wildlife conservation and ecosystem restoration @newsomeResolvingValueDingo2015]. As aforementioned in an example by @letnicTopPredatorsBiodiversity2012, the idea of dingoe re-introduction is based on theories and results of studies suggesting that the presence of the dingoe can suppress mesopredators such as red foxes and feral cats, in turn benefiting small prey by reducing overall predation pressure. In addition, the suppressive effects of the dingoe may extend towards medium-sized grazers (e.g., feral goats and kangaroos), when in high densities, can contribute signifcantly to vegetation degradation in most natural landscapes [@letnicTopPredatorsBiodiversity2012]. Therefore, the question lies as to whether the free-roaming domestic dog, with its similarities to its wilder counterparts (e.g., dingoes and their hybrids), may exert similar predation pressures through an ecosystem and yet contribute to native biodiversity conservation (e.g., mesopredator and prey suppression) in a similar fragmented landscape (i.e., lack of an apex terrestrial predator).

# The Movement Ecology framework for research

Movement is a fundamental characteristic in life, driven by the processes that determines the fate of individuals, and the structure and dynamics of populations, communities and ecosystems. Causal links between organismal movement patterns and environmental change or degradation are highlighted by the interactions between anthropogenic habitat fragmentation (or degradation), changes climate and land-use patterns, and the (intentional) introduction of invasive species. Therefore, having a cohesive understanding of the causes, patterns, mechanisms and consequences of organismal movement can be instrumental in controlling the spread of pests, invasive alien species, and infectious diseases, and managing and restoring degraded landscapes.

Scientific information pertaining to the movement patterns of the free-roaming dog is limited and one-dimensional despite the limited availability of information on their potential impacts and interactions with wildlife [@hughesReviewInteractionsFreeroaming2013]. For example,  @atickemCompetitionDomesticDogs2009 concluded that dogs were unlikely to be a serious threat towards the Ethiopian wolf (*C. siamensis*) by arguing that the wolves and dogs had a lack of overlap in diet composition and spatial proximity between both species. However, their findings could be better supported if other facets of the studied dog movement, such as the temporality, were examined to 1) identify the circadian and activity patterns in dogs, and 2) further affirm the lack of temporal overlap between wolf and dog movement. This notion of examining not only the "where", but the "how", "when", and "why" of movement is the core concept within the Movement Ecology framework.

Movement Ecology is a recently developed framework that has been gaining significant traction with more recent ecological studies [@holdenInchingMovementEcology2006]. This framework of research aims to examine the spatial behaviour of an organism through a single unified theory with the use of large and diverse datasets (e.g., accelerometry readings, Global Positioning System re-locations). Recent advancement in modern telemetry systems have allowed researchers to collect substantial volumes of high-resolution data on the movement patterns of animals. The collection of such data not only offers a better understanding of the movement patterns of animals at varying spatial and temporal scales, it also provides researchers with an in-depth insight into the effects of the physiological, demographic, and ecological contexts on spatial behaviour [@wilmersGoldenAgeBiologging2015].

As an animal's decision to move results from the complex interactions between intrinsic and extrinsic factors, the Movement Ecology framework examines the mechanisms in the animal's movement path through four main components: the internal state, the motion and navigational capacity, and external factors. The ‘internal state’ refers to the physiological state and associated motivation for an organism to move. in the case of the free-roaming dog, the 'internal state' refers to the intrinsic (i.e., driven by cognitive ability, assessing resources, learning the environment) and/or extrinsic (i.e., driven by physiological state; e.g., hunger, escape from predation) form of motivation that determines the movement path. The ‘motion capacity’ describes the biomechanical means of movement (e.g., running, walking or resting) and the ‘navigational capacity’ refers to the dog’s ability to orient itself in space and time given its sensory or cognitive capacity (e.g., dens, latrines, watering holes). Lastly, the ‘external factors’ refer to the biotic and abiotic components within an environment that influences the movement of said animal (e.g., anthropogenic disturbances, climatic conditions). Therefore, by examining the free-roaming dogs' movement through these four components, the framework allows researchers to understand the causes, mechanisms, and patterns of movement at the individual, population, and community level.

To examine the free-roaming dogs extent of interaction with wildlife (e.g., predation, harrassment), @vanakDogsCanisFamiliaris2009 suggests that the dog's capacity to roam freely and the location of the studied dog are important factors to consider as they have direct implications on the likelihood and frequency of any probable wildlife interaction. For example, dogs with constrained movements within urban landscapes (e.g., pet dogs) are less likely to interact with wildlife in comparison to unconstrained dogs (freely roaming) in natural or rural landscapes. As most dogs are also highly dependant on human-derived supplementary resources, it may also be equally important to consider their direct and indirect access to non-wild food sources to further define the extent of interaction between dog and wildlife.

With the proposed considerations mentioned above, one could characterize and predict the type of dog-wildlife interaction based on the dogs' range of movement into vulnerable landscapes as well as their varied levels of dependencies on supplementary resources. For example, @atickemCompetitionDomesticDogs2009 and @bayarbaatarMongolianSaigaSharga2009 reported that free-roaming dogs and were less significant threats to wildlife (Ethiopian wolf; *C. siamensis*, Mongolian saiga; *Saiga tatarica mongolica*) as they had small home ranges and stayed within close proximity to human settlements while being heavily dependant on human-derived resources. Conversely, @sepulvedaDomesticDogsRural2014 reported that dog interactions with prey species in the temperate forests of Chile appeared to be driven by hunger  while @ruiz-izaguirreVillageDogNot2013 reported that 'feral dogs' independent of humans were found further away from households, had larger mean activity range and scavenged more readily on turtle nests. Unfortunately, the aforementioned studies were conducted through interviews and focal surveys and did not specifically examine the contextual context of movement patterns in the studied dogs. 

# Applying the Movement Ecology framework

Movement allows an animal to search for important resources such as shelter, food and mates, and to avoid risk factors such as predators or any other form of danger (e.g., forest fires, human presence). This pattern of movement in an individual animal is used to describe a finite area termed as a home range. One widely cited definition of an animal’s home range is by @burtTerritorialityHomeRange1943: ‘that area traversed by the individual in its normal activities of food gathering, mating and caring for you. Occasional sallies outside the area, perhaps exploratory in nature, should not be considered as in part of the home range.’ However, the definition presented by Burt demonstrates several problems. Firstly, an ‘occasional sally’ can only be defined when the home range of an animal has already been well-established, and secondly, Burt’s definition does not recognise the importance of variations in the intensity or patterns of space use within a home range [@kieHomerangeConceptAre2010]. Therefore, the definition of an animal's home range should be more than just a simple estimation of the area traversed, it should also include the interpretation and quantification of the animals' patterns space use within said estimated area.

Despite the long history in studying animal movement patterns in ecology, progress within the field of animal movement studies has been slow as data gathered from wild individuals were often sparse and inconsistent which can make accurate home range estimation difficult and inaccurate [@habibThreeDecadesWildlife2014]. Traditionally, researchers would monitor individual animals with the use of VHF (Very High Frequency) radiotelemetry and estimate their home range by plotting the movements of said individual over a period of time onto a map. However, there are several drawbacks to using VHF radiotelemetry in the study of animal movement. Firstly, the animal may not necessarily visit all areas within its home range during the study period, and the quality (e.g., volume and accuracy) of the data collected from the observational period is dependent on the researcher’s ability (e.g., catching up with fast-moving animals) and availability (e.g., labour-intensive). In addition, the presence of the researcher during radio-telemetry can result in unnatural movement behaviours that can mis-represent the natural tendencies of the studied animal. In short, the information collected via traditional radio-telemetry is often lower in volume, lesser in detail and of poorer accuracy. 

The many advances in GPS technologies have provided researchers the opportunity to use GPS loggers to monitor animal movements in wildlife telemetry studies. This has resulted in the collection of the studied animal's spatial information where datasets are not only numerous and precise, but also highly correlated between space and time. Having access to the temporal information provided by GPS locations provides a window of opportunity to examine the patterns of space use in the studied animal. However, to do so, researchers would need alter or change their use traditional home range estimators that were developed initially for the smaller datasets obtained from VHF radio-telemetry. Therefore, researchers are now not only challenged with managing large volumes of information (> 10,000 location per animal), they are also tasked with selecting the most appropriate and functional home-range estimator for the analysis of home range sizes or movement patterns with the increased volume of GPS re-locations.

Through the rapid miniaturisation of electronic sensors (i.e., accelerometers), the field of wildlife radio-telemetry is slowly approaching yet another growth spurt as  GPS technologies are coupled with the use of sensors that can contiuously measure most aspects of an animal's state (e.g., heart rate, acceleration) and external environment (e.g., temperature, depth). For example, researchers have incorporated animal-borne transmitters with light and temperature sensors [@wilsonPryingIntimateDetails2008], digital and video cameras [@loydQuantifyingFreeroamingDomestic2013], and more recently, tri-axial accelerometers [@lushUseTriaxialAccelerometers2016; @williamsIdentificationAnimalMovement2017]. These additions to wildlife telemetry, termed as 'bio-loggers' [@wilmersGoldenAgeBiologging2015], are paramount to understanding the ecology of an animal by giving researchers the opportunity to not only describe behavioural contexts that were previously unobservable (e.g., fossorial or flying animals), they also provide researchers an opportunity to answer new questions about the physiological performance, energetics, movement patterns, and sociality of wild animals, as well as collect data on the environments in which they live.

One method of circumventing the constraints of directly observing animals in the wild comes with the use of tri-axial accelerometers [@williamsIdentificationAnimalMovement2017]. Tri-axial accelerometers allow researchers to characterise an animal's movement patterns and behaviours by recognising the gravitational (static) and inertial (dynamic) acceleration caused by movement. As the three axes in an accelerometer are aligned orthogonally (to one another), researchers are able to quantify and realistically represent the three-dimensional movement or posture of an animal from acceleration forces measured simultaneously across the three seperate axes (X, Y and Z; heave, surge and sway, respectively). This form of bio-logging, even though in its infancy stages with terrestrial animals (see @lushUseTriaxialAccelerometers2016), have already been explored with wild animals such as pumas (*Puma concolor*;@wangMovementRestingAttack2015), Eurasian badgers (*Meles meles*;@mccluneTriaxialAccelerometersQuantify2014), as well as domestic species such as dairy cows [@vazquezdiosdadoClassificationBehaviourHoused2015] and sheep [@maraisAutomaticClassificationSheep2014]. More importantly, acceleration sensors offers fine-scale information on the variation and extent of animal behavior, and energy expenditure in space and time when used with GPS re-locations [@hammondUsingAccelerometersRemotely2016; @resheffTopicModelingBehavioral2016].

Having access to developing bio-logging technologies has brought the study of animal movement and ecology into the realm of big data science [@kaysTerrestrialAnimalTracking2015] where the voluminous size of collected movement data grows exponentially from longer sampling durations (i.e., increased battery life and storage capacity) and the wider combination of collectible biologging data types used (i.e, GPS, acceleration, video recordings). Despite the easy availability of such technologies accessible by movement researchers, the processing and use of these data can be time-consuming and difficult. For example, accelerometers can be used to identify movement patterns and behavioural states through changes in activity but most studies are limited to simple threshold-based detection of active/inactive states [@hammondUsingAccelerometersRemotely2016] or classification into slightly richer behavioural states [@battaileAccelerometersIdentifyNew2015; @vazquezdiosdadoClassificationBehaviourHoused2015]. This is particulary relevant for studies species that are near to impossible to follow and observe [@araiiAnalysisDivingBehavior2000; @carrollSupervisedAccelerometryAnalysis2014; @yasudaChangesFlipperBeat2009], as such it can difficult to draw true behaviours from such analysis.

Rather than using arbitrary values and thresholds to identify behavioural states, it is possible for one to combine and associate the collected acceleration values to observations of the studied actual animal behaviour to draw more robust conclusions on the animal's true behaviour. Through this notion of analysis, researchers can address detailed behavioural questions on elusive, far-ranging species that do not occur in high densities (e.g., rare species) and/or are difficult to monitor continously (e.g., challenging terrain or landscape). However, the collection of behavioural and accelerometer data can be extremely time-consuming and the volume of the both collected datasets (accelerometer and behavioural observations) can be too large to process by hand. As such, researchers are steadily resorting to the use of Machine Learning Algorithms (MLAs) to address this challenge [@bidderLoveThyNeighbour2014; @resheffTopicModelingBehavioral2016; @sakamotoCanEthogramsBe2009].

Generally, there are two main approaches to building MLA models to predict movement behaviour or patterns from using accelerometery outputs. The first approach is the unsupervised classification method where movement patterns are characterised by grouping similar-looking accelerometery outputs either through visual inspection of the data, or by using statistical methods such as *k* means clustering or *k* nearest neighbour algorithm [@bidderLoveThyNeighbour2014; @sakamotoCanEthogramsBe2009]. Going with the unsupervised approach to MLA model building is often easier and can be readily applied to new or pre-existing datasets without the need to ground-truth the information. However, the challenge with unsupervised MLA models lies in their inability to explain the differentiation between predicted behaviour states (without ground-truthing), and it's inability to specifically detect and predict fine-scale behaviours. For example, @sakamotoCanEthogramsBe2009 could only detect movement-related behaviours (e.g., dive, foraging) and not motionless behaviours (e.g., rest) as the unsupervised approach was unable to differentiate between the different postures of the tracked animal.

As for the second approach, the supervised method of constructing predictive MLA models involves ‘training’ the MLA model on segments of accelerator outputs that have been classified with behaviour labels after direct observation of the animal tagged with an accelerometer [@resheffTopicModelingBehavioral2016]. These ground-truth models can then be used to predict and classify unobserved behaviours from new accelerometer outputs into the pre-determined behaviour labels used for training the model. With sufficient training on computationally powerful models (e.g., random forest), intrinsic differences in the accelerometery outputs of similar-looking behaviour or movement patterns can be identified [@resheffTopicModelingBehavioral2016]. Hence, the supervised learning approach would be the most ideal approach for the purpose of examining the movement patterns of free-roaming dogs. This is primarily due to the access to domestic dogs, which can be used as ground-truth models to train and validate the collected accelerometery outputs. Furthermore, this access to ground-truth models allows the identification of coarse or fine-scale behaviours of interest (e.g., foraging, resting) for the training and construction of MLA models.

Despite its application on to many species, and for a diverse range of behavioural states and patterns, there are several drawbacks to using the supervised approach to MLA model construction. Pre-determined behaviour labels, even if observed and prepared perfectly, may not be adequately representative of the behavioral pattern of the studied animal throughout the period of the research. In the case of non-captive individuals, tedious amounts of fieldwork may still be required to obtain sufficient enough observations, and the presence of the observer may have an impact on the natural behaviour of the observed animal. More importantly, the need for observations limits the scope of such research projects to observable species and to research labs with the necessary resources (in money, manpower, and knowledge) to carry out all the
steps listed above.

# Thesis layout

In chapter 1, I focus on optimising the predictive MLA models used in the research project and the determination of the accelerometer thresholds necesary for moderating the frequency of GPS re-location collection in the wildlife tracking collar. The chapter mostly discusses the procedures involved in the model construction phase (e.g., training data collection, data labelling and transformation, model building and validation), and how it will be used to identify the accelerometer threshold in the wildlife tracking collar. As with most field-based research work, optimising field equipment and procedures not only improves the accuracy and sampling duration of field data collection, it also allows for the collection of more biologically relevant information from the studied animals.

Chapter 2 explores the use of the constructed MLA model to predict the behavioural states and patterns of the collared free-roaming dogs from each study site. In addition, the chapter also examines the circadian rhythm of these animals with the use of the MLA model predictions, and the external factors that have influences on the peaks and troughs of the dogs' circadian pattern. As very little is known about the circadian pattern of these animals, to have an understanding of the dogs' circadian pattern not only informs us of their ecology, it also allows us to examine their potential impact on native wildlife.

For chapter 3, I will be examining the movement patterns of these free-roaming animals by estimating the home range sizes and shapes from GPS information collected from the free-roaming dogs of Singapore. To draw different biological interpretation in the spatial distribution of these animals, this chapter will use the spatial and temporal information present in GPS re-locations to explore intensity of space use (e.g., utilisation distribution), directionaility (e.g., step selection analysis) and extent of movement (e.g., minimum convex polygons) in dogs. With the findings from the earlier chapter, I will be exploring how the dogs' circadian rhythm as well as the various environmental factors (e.g., intrinsic site-specific differences) that may influence the movement patterns of these animals.

Chapter 4 attempts to identify and explore the habitat preferences of the free-roaming dog by is performed by mapping GPS re-locations and the home range shapes estimated from the earlier chapter onto a raster Geopgraphic Information systems (GIS) layer of the various study sites. In addition, this chapter will attempt to construct an 'activity landscape' to identify the spatial distribution of movement behaviours that are deemed impactful to wildlife. An activity landscape differentiates itself from the basic habitat selection analysis by specifically examining where impactful behaviour occurs. This is done by identifying GPS locations that are predicted to be impactful (i.e., running, foraging, eating) and then mapping the frequency and extent of these occurrences. Information such as this provides a more in-depthful and meaningful examination into the relative impact of the free-roaming dog on native wildlife. 
In the final chapter, I will be exploring the energetic expenditure of the these free-roaming dogs through the use of a commonly used proxy, the Overall Body Dynamic Acceleration (OBDA; @wilsonMovingAccelerationEstimates2006). The ODBA method proposes that, since the most (and in many cases the major) variable factor in modulating energy expenditure in many vertebrates is movement, then the measurement of bodily acceleration (through tri-axial accelerometer) should correlate with energetic expenditure. For this research project, each GPS re-location was obtained alongside a sequence of acceleration outputs, hence I could determine the OBDA value of each GPS re-location and derive the energetic cost of the dogs moving through the landscape. Subsequently, by mapping the dogs' energetic expenditure (through GPS re-locations), I can identify the energetic expenditure of the different routes taken through the landscape to get an insight on how the environment and landscape influences the dogs' spatial use.

Collectively, the research project aims to use the aforementioned five chapters to examine the movement ecology of the free-roaming dog in Singapore by addressing the where, when, why, and how of movement. Using the framework as a guide, the chapters will be able to examine the relative impact and the potential role of the free-roaming dog in natural areas. Understanding how dogs interact within their inhabited natural landscape is an important tool to managing wildlife conservation efforts, as well as dog management programs in Singapore. Dissemination of these chapters through publication in peer-reviewed journals will also be useful to natural resource managers, wildlife conservationist, animal welfare groups, and other interested stakeholders to help guide control and management plans to help reduce dog-wildlife conflicts and transform indiscriminant dog removal and control into more ecologically justifiable dog management.

\newpage

# References